In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.5806489])

In [14]:
np.random.rand(5,2)

array([[0.30797321, 0.31241928],
       [0.71084594, 0.02274709],
       [0.90188792, 0.70399485],
       [0.29660258, 0.42565795],
       [0.20554643, 0.69455043]])

In [15]:
np.random.randn(10)

array([-0.2748978 , -0.39491165, -1.03722434,  1.12444284, -0.22883536,
        1.90340029, -1.24378882, -1.49351575, -1.20193928,  1.2182252 ])

In [17]:
np.random.randn(2,3)

array([[ 0.82116117,  0.85135897, -0.90253104],
       [ 1.00707442,  0.40252195, -0.21356571]])

In [18]:
np.random.randint(0,101,10)

array([92, 96, 66, 39,  8, 46, 53, 73, 26, 93])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
arr = np.arange(0,25)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr = np.random.randint(0,101,10)

In [24]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [25]:
ranarr.max()

99

In [26]:
ranarr.min()

2

In [27]:
ranarr.argmax()

5

In [28]:
ranarr.argmin()

7

In [29]:
ranarr.dtype


dtype('int64')

In [30]:
arr.shape

(25,)

In [31]:
arr = arr.reshape(5,5)

In [32]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.sum()

300

In [34]:
arr.sum(axis=0)
# suma en forma vertical 

array([50, 55, 60, 65, 70])

In [35]:
arr.sum(axis =1)

array([ 10,  35,  60,  85, 110])

In [37]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])